
on:
 push:
  branches:
    - test





jobs:
  build:
    runs-on: ubuntu -latest

    steps:
      - uses: action/checkout@v3 
      
      - name: "Login to docker hub"
        run: docker login --username mohamed011 --password dckr_pat_H7Ic2sNv6BROiLKsRpxLzyUwxQE


